In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
a =(1,2,3,4,5)

print(a)

(1, 2, 3, 4, 5)


In [3]:
type(a)

tuple

In [4]:
b= np.array(a)
print(b)

[1 2 3 4 5]


In [5]:
type(b)

numpy.ndarray

In [6]:
b.ndim

1

In [7]:
b.size

5

In [8]:
b.shape

(5,)

In [9]:
import time as tm

size_1 = 10000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 5.657954692840576
numpy = 0.08545994758605957


In [10]:
my_list=[2,3,4,6,7,8]

In [11]:
my_array=np.array(my_list)
my_array

array([2, 3, 4, 6, 7, 8])

In [12]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [13]:
array_3.ndim

2

In [14]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array_3.size

9

In [16]:
array_3.shape

(3, 3)

In [17]:
a = np.array([1, 2, 3,7,5,1], ndmin = 3) 
print (a)
np.ndim(a)

[[[1 2 3 7 5 1]]]


3

In [18]:
a = np.array([1, 2, 3,7,5,1], ndmin = 8) 
print (a)
np.ndim(a)

[[[[[[[[1 2 3 7 5 1]]]]]]]]


8

In [19]:
array_3[0]

array([1, 2, 3])

In [20]:
array_3[1]

array([4, 5, 6])

In [21]:
array_3[2,0]

7

In [23]:
array_3[:,1] # Acessing Column

array([2, 5, 8])

In [22]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,3) #(start,end,space)

array([1, 4, 7])

In [26]:
np.arange(10,100,5) #(start,end,space)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [27]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [28]:
np.linspace(1,4,10) # (start,end,no of values)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [29]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [30]:
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [31]:
np.random.rand(2)

array([0.05321084, 0.18631097])

In [32]:
np.random.rand(20)

array([0.03178443, 0.37172309, 0.35977244, 0.14799108, 0.17849616,
       0.02172495, 0.2685924 , 0.01861962, 0.06758106, 0.30331532,
       0.84837144, 0.77024026, 0.80511735, 0.26863678, 0.08278674,
       0.44465826, 0.2912161 , 0.21602733, 0.48489439, 0.70597057])

In [33]:
np.random.rand(2,2)

array([[0.2297917 , 0.85797138],
       [0.56358927, 0.37721338]])

In [34]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [38]:
x.reshape(2, 8)

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12, 13]])

In [39]:
x.reshape(8, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10],
       [10, 11],
       [12, 13]])

In [40]:
x.reshape(8, 3)

ValueError: cannot reshape array of size 16 into shape (8,3)

In [41]:
x.reshape(16, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [10],
       [11],
       [12],
       [13]])

In [42]:
x.min()

1

In [43]:
x.max()

13

In [45]:
x.mean()

7.0

In [46]:
x.std()

3.5355339059327378

In [47]:
x.var()

12.5

In [48]:
x.sum()

112

In [49]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [51]:
x.min(axis=1)

array([ 1,  4,  7, 10])

In [52]:
x.min(axis=0)

array([1, 2, 3, 4])

In [53]:
x.flatten() #2D to 1D

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [54]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [55]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [56]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [57]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [58]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
A+B

array([[ 5., 11., 12.],
       [22., 23., 24.],
       [32., 33., 34.]])

In [60]:
A-B

array([[ 3.,  9., 10.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [61]:
A*B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [62]:
B/A

array([[0.25      , 0.1       , 0.09090909],
       [0.04761905, 0.04545455, 0.04347826],
       [0.03225806, 0.03125   , 0.03030303]])

In [63]:
B%A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
A*2

array([[ 8, 20, 22],
       [42, 44, 46],
       [62, 64, 66]])

In [65]:
A**2

array([[  16,  100,  121],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

In [66]:
np.dot(A,B)

array([[25., 25., 25.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [67]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [68]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [70]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [71]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [72]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print (np.around(a)) 

[[12. 24.]
 [33. 46.]]


In [73]:
a

array([[11.667, 23.662],
       [33.21 , 45.887]])

In [76]:
print (np.around(a, decimals = 1))

[[11.7 23.7]
 [33.2 45.9]]


In [77]:
np.concatenate([a,b])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [80]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [81]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
np.concatenate([A,B])

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [83]:
np.random.randint(2,10,(3,4))

array([[5, 4, 6, 5],
       [9, 7, 7, 9],
       [6, 5, 8, 8]])

In [84]:
np.random.rand(5,4)

array([[0.13570036, 0.77982366, 0.50498644, 0.58579955],
       [0.30615442, 0.60610801, 0.47135867, 0.24233084],
       [0.80208181, 0.79226054, 0.2013439 , 0.23536308],
       [0.18859573, 0.07798767, 0.98615704, 0.59729073],
       [0.32853595, 0.39526437, 0.30531502, 0.90360743]])

In [85]:
a =np.random.randn(4,4)

In [86]:
a

array([[-0.50054726,  2.45151493, -1.16729509,  0.97330505],
       [ 2.22710444, -0.56822962, -0.43171107,  0.38104154],
       [ 1.31869907, -0.95187432, -0.4815931 , -0.46637538],
       [ 1.08176724, -2.11342855, -0.65445274,  2.21620718]])

In [87]:
import pandas as pd

In [88]:
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math': [88, 92, 85, 78],
    'Science': [90, 85, 88, 92],
    'English': [85, 95, 80, 88]
}

In [89]:
data

{'Student': ['Alice', 'Bob', 'Charlie', 'David'],
 'Math': [88, 92, 85, 78],
 'Science': [90, 85, 88, 92],
 'English': [85, 95, 80, 88]}

In [90]:
df = pd.DataFrame(data)

In [91]:
df

Student  Math  Science  English
0    Alice    88       90       85
1      Bob    92       85       95
2  Charlie    85       88       80
3    David    78       92       88

In [92]:
# Calculate the average score for each student using NumPy
df['Average'] = np.mean(df[['Math', 'Science', 'English']], axis=1)

In [93]:
df

Student  Math  Science  English    Average
0    Alice    88       90       85  87.666667
1      Bob    92       85       95  90.666667
2  Charlie    85       88       80  84.333333
3    David    78       92       88  86.000000

In [94]:
# Find the highest average score using NumPy
highest_average = np.max(df['Average'])

In [95]:
highest_average

90.66666666666667

In [96]:
# Get the name of the student with the highest average
top_student = df.loc[df['Average'] == highest_average, 'Student'].values[0]

In [97]:
top_student

'Bob'

In [99]:
df.loc[1:2]

Student  Math  Science  English    Average
1      Bob    92       85       95  90.666667
2  Charlie    85       88       80  84.333333

In [104]:
df.loc[1:2, ["Math", "English"]]

Math  English
1    92       95
2    85       80

In [107]:
df1 =pd.read_csv("C:\\Users\\amitm\\Downloads\\sales_data_final.csv")

In [108]:
df1.shape

(51290, 21)

In [110]:
df1.loc[10:30]

order_id order_date  ship_date       ship_mode      customer_name  \
10    IN-2011-65159   1/3/2011   1/7/2011    Second Class       Larry Blacks   
11    IN-2011-65159   1/3/2011   1/7/2011    Second Class       Larry Blacks   
12  ES-2011-4869686   1/3/2011   1/7/2011  Standard Class  Dorothy Dickinson   
13    IN-2011-33652   1/3/2011   1/9/2011  Standard Class      Dennis Pardue   
14    ID-2011-80230   1/3/2011   1/9/2011  Standard Class       Ken Lonsdale   
15   MX-2011-160234   1/3/2011   1/7/2011  Standard Class   Stewart Visinsky   
16      IR-2011-770   1/3/2011   1/7/2011  Standard Class      Jas O'Carroll   
17    ID-2011-80230   1/3/2011   1/9/2011  Standard Class       Ken Lonsdale   
18    ID-2011-80230   1/3/2011   1/9/2011  Standard Class       Ken Lonsdale   
19    ID-2011-12596   1/3/2011   1/8/2011  Standard Class       Chris McAfee   
20    IN-2011-79397   1/3/2011   1/3/2011        Same Day        Kean Nguyen   
21     IR-2011-7690   1/3/2011   1/8/2011    Second Class         Nat Gilpin   
22      IR-2011-770   1/3/2011   1/7/2011  Standard Class      Jas O'Carroll   
23     TZ-2011-7370   1/3/2011   1/8/2011  Standard Class         Jack Garza   
24     IZ-2011-4680   1/3/2011   1/7/2011  Standard Class   Lindsay Williams   
25    IN-2011-65159   1/3/2011   1/7/2011    Second Class       Larry Blacks   
26      IR-2011-770   1/3/2011   1/7/2011  Standard Class      Jas O'Carroll   
27   MX-2011-111255   1/4/2011   1/9/2011    Second Class  Russell Applegate   
28   MX-2011-140641   1/4/2011   1/9/2011  Standard Class        Maya Herman   
29   MX-2011-158771   1/4/2011  1/11/2011  Standard Class      Beth Thompson   
30  ES-2011-4939443   1/4/2011   1/8/2011  Standard Class     Arthur Prichep   

        segment              state         country  market          region  \
10     Consumer   National Capital     Philippines    APAC  Southeast Asia   
11     Consumer   National Capital     Philippines    APAC  Southeast Asia   
12     Consumer            England  United Kingdom      EU           North   
13  Home Office            Sarawak        Malaysia    APAC  Southeast Asia   
14     Consumer           Auckland     New Zealand    APAC         Oceania   
15     Consumer          Guatemala       Guatemala   LATAM         Central   
16     Consumer               Yazd            Iran    EMEA            EMEA   
17     Consumer           Auckland     New Zealand    APAC         Oceania   
18     Consumer           Auckland     New Zealand    APAC         Oceania   
19     Consumer  Nakhon Ratchasima        Thailand    APAC  Southeast Asia   
20    Corporate    New South Wales       Australia    APAC         Oceania   
21    Corporate    Razavi Khorasan            Iran    EMEA            EMEA   
22     Consumer               Yazd            Iran    EMEA            EMEA   
23     Consumer      Dar Es Salaam        Tanzania  Africa          Africa   
24    Corporate             Ninawa            Iraq    EMEA            EMEA   
25     Consumer   National Capital     Philippines    APAC  Southeast Asia   
26     Consumer               Yazd            Iran    EMEA            EMEA   
27     Consumer             Parana          Brazil   LATAM           South   
28    Corporate            Yucat n          Mexico   LATAM           North   
29  Home Office             Granma            Cuba   LATAM       Caribbean   
30     Consumer        Rh“ne-Alpes          France      EU         Central   

    ...         category sub_category  \
10  ...  Office Supplies      Storage   
11  ...        Furniture       Tables   
12  ...        Furniture    Bookcases   
13  ...       Technology      Copiers   
14  ...        Furniture       Chairs   
15  ...       Technology       Phones   
16  ...  Office Supplies   Appliances   
17  ...       Technology  Accessories   
18  ...        Furniture       Chairs   
19  ...  Office Supplies      Storage   
20  ...  Office Supplies       Labels   
21  ...  Office Supplies          Art   


In [111]:
df1.loc[10:30:3]

order_id order_date ship_date       ship_mode  customer_name  \
10   IN-2011-65159   1/3/2011  1/7/2011    Second Class   Larry Blacks   
13   IN-2011-33652   1/3/2011  1/9/2011  Standard Class  Dennis Pardue   
16     IR-2011-770   1/3/2011  1/7/2011  Standard Class  Jas O'Carroll   
19   ID-2011-12596   1/3/2011  1/8/2011  Standard Class   Chris McAfee   
22     IR-2011-770   1/3/2011  1/7/2011  Standard Class  Jas O'Carroll   
25   IN-2011-65159   1/3/2011  1/7/2011    Second Class   Larry Blacks   
28  MX-2011-140641   1/4/2011  1/9/2011  Standard Class    Maya Herman   

        segment              state      country market          region  ...  \
10     Consumer   National Capital  Philippines   APAC  Southeast Asia  ...   
13  Home Office            Sarawak     Malaysia   APAC  Southeast Asia  ...   
16     Consumer               Yazd         Iran   EMEA            EMEA  ...   
19     Consumer  Nakhon Ratchasima     Thailand   APAC  Southeast Asia  ...   
22     Consumer               Yazd         Iran   EMEA            EMEA  ...   
25     Consumer   National Capital  Philippines   APAC  Southeast Asia  ...   
28    Corporate            Yucat n       Mexico  LATAM           North  ...   

           category sub_category                    product_name sales  \
10  Office Supplies      Storage       Tenex Lockers, Industrial   338   
13       Technology      Copiers   Hewlett Fax and Copier, Laser   193   
16  Office Supplies   Appliances  Breville Coffee Grinder, Black   123   
19  Office Supplies      Storage           Smead File Cart, Blue   135   
22  Office Supplies      Storage      Rogers Folders, Industrial    62   
25  Office Supplies    Fasteners        Stockwell Staples, Metal     6   
28       Technology  Accessories     Enermax Keyboard, Bluetooth   223   

   quantity  discount    profit  shipping_cost  order_priority  year  
10        3      0.45 -122.8005          33.75            High  2011  
13        1      0.00   50.1300          10.40          Medium  2011  
16        2      0.00   42.9000           8.41          Medium  2011  
19        2      0.47  -45.9018           7.74          Medium  2011  
22        2      0.00    8.7000           5.16          Medium  2011  
25        1      0.45    0.5460           0.80            High  2011  
28        4      0.00   13.2800          42.28            High  2011  

[7 rows x 21 columns]

In [112]:
df1.loc[10:30:3, ["segment", "country", "sub_category"]]

segment      country sub_category
10     Consumer  Philippines      Storage
13  Home Office     Malaysia      Copiers
16     Consumer         Iran   Appliances
19     Consumer     Thailand      Storage
22     Consumer         Iran      Storage
25     Consumer  Philippines    Fasteners
28    Corporate       Mexico  Accessories

In [113]:
df1.iloc[10:30:3]

order_id order_date ship_date       ship_mode  customer_name  \
10   IN-2011-65159   1/3/2011  1/7/2011    Second Class   Larry Blacks   
13   IN-2011-33652   1/3/2011  1/9/2011  Standard Class  Dennis Pardue   
16     IR-2011-770   1/3/2011  1/7/2011  Standard Class  Jas O'Carroll   
19   ID-2011-12596   1/3/2011  1/8/2011  Standard Class   Chris McAfee   
22     IR-2011-770   1/3/2011  1/7/2011  Standard Class  Jas O'Carroll   
25   IN-2011-65159   1/3/2011  1/7/2011    Second Class   Larry Blacks   
28  MX-2011-140641   1/4/2011  1/9/2011  Standard Class    Maya Herman   

        segment              state      country market          region  ...  \
10     Consumer   National Capital  Philippines   APAC  Southeast Asia  ...   
13  Home Office            Sarawak     Malaysia   APAC  Southeast Asia  ...   
16     Consumer               Yazd         Iran   EMEA            EMEA  ...   
19     Consumer  Nakhon Ratchasima     Thailand   APAC  Southeast Asia  ...   
22     Consumer               Yazd         Iran   EMEA            EMEA  ...   
25     Consumer   National Capital  Philippines   APAC  Southeast Asia  ...   
28    Corporate            Yucat n       Mexico  LATAM           North  ...   

           category sub_category                    product_name sales  \
10  Office Supplies      Storage       Tenex Lockers, Industrial   338   
13       Technology      Copiers   Hewlett Fax and Copier, Laser   193   
16  Office Supplies   Appliances  Breville Coffee Grinder, Black   123   
19  Office Supplies      Storage           Smead File Cart, Blue   135   
22  Office Supplies      Storage      Rogers Folders, Industrial    62   
25  Office Supplies    Fasteners        Stockwell Staples, Metal     6   
28       Technology  Accessories     Enermax Keyboard, Bluetooth   223   

   quantity  discount    profit  shipping_cost  order_priority  year  
10        3      0.45 -122.8005          33.75            High  2011  
13        1      0.00   50.1300          10.40          Medium  2011  
16        2      0.00   42.9000           8.41          Medium  2011  
19        2      0.47  -45.9018           7.74          Medium  2011  
22        2      0.00    8.7000           5.16          Medium  2011  
25        1      0.45    0.5460           0.80            High  2011  
28        4      0.00   13.2800          42.28            High  2011  

[7 rows x 21 columns]

In [114]:
df1.iloc[10:30:3, 1:20:3]

order_date  customer_name      country        product_id  \
10   1/3/2011   Larry Blacks  Philippines   OFF-ST-10003020   
13   1/3/2011  Dennis Pardue     Malaysia   TEC-CO-10000594   
16   1/3/2011  Jas O'Carroll         Iran  OFF-BRE-10003081   
19   1/3/2011   Chris McAfee     Thailand   OFF-ST-10002066   
22   1/3/2011  Jas O'Carroll         Iran  OFF-ROG-10004393   
25   1/3/2011   Larry Blacks  Philippines   OFF-FA-10002569   
28   1/4/2011    Maya Herman       Mexico   TEC-AC-10001082   

                      product_name  discount order_priority  
10       Tenex Lockers, Industrial      0.45           High  
13   Hewlett Fax and Copier, Laser      0.00         Medium  
16  Breville Coffee Grinder, Black      0.00         Medium  
19           Smead File Cart, Blue      0.47         Medium  
22      Rogers Folders, Industrial      0.00         Medium  
25        Stockwell Staples, Metal      0.45           High  
28     Enermax Keyboard, Bluetooth      0.00           High

In [121]:
df1.iloc[1,2]

'1/8/2011'

In [122]:
df1

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   